services:
  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer
      - GF_FEATURE_TOGGLES_ENABLE=alertingSimplifiedRouting,alertingQueryAndExpressionsStepMode
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy 
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    image: grafana/grafana:11.6.0
    container_name: grafana
    ports:
      - 3000:3000
    networks:
      - loki
  
  promtail:
    image: grafana/promtail:main-590c391
    container_name: promtail
    volumes:
      - ./log/:/var/log
      - ./promtail-config.yml:/etc/promtail/config.yml
    ports:
      - 9080:9080
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki

  loki:
    image: grafana/loki:main-590c391
    container_name: loki
    networks:
      - loki
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml
    
networks:
  loki:

