server:
  http_listen_port: 3100

positions:
  filename: /tmp/positions.yaml

scrape_configs:
- job_name: petclinic
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/spring-petclinic.log